//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceLaptopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public int Lid { get; set; }
        public string LName { get; set; }
        public string LCore { get; set; }
        public string LSpace { get; set; }
        public string LPrice { get; set; }
        public string MsOffce { get; set; }
        public Nullable<int> Model_Id { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual ModelType ModelType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
